name: ift6758-conda-env
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - requests
  - tqdm
  - opencv
  - lxml
  - ipykernel
  - ipywidgets
  - jupyterlab>=3.0.0
  - ipdb
  - setuptools
  - scipy
  - bokeh
  - nbformat
  - jsonschema
  - python-dotenv
  - pip
 
